import { CommonModule } from '@angular/common';
import { Component } from '@angular/core';
import { ListingCardComponent } from '../listing-card/listing-card.component';

@Component({
  selector: 'app-listing-page',
  standalone: true,
  imports: [CommonModule,ListingCardComponent],
  templateUrl: './listing-page.component.html',
  styleUrl: './listing-page.component.scss'
})
export class ListingPageComponent {
  hotels = [
    {
      id: 1,
      featured: true,
      priceRange: "$25 - $35",
      rating: 5,
      reviews: 7,
      name: "Daanyal bilobrs",
      verified: true,
      description: "Luxury billboard in the heart of Bloomsbury.",
      location: "Santa Monica, CA",
      phone: "+61 2 8236 9200",
      category: "Billboard",
      additionalCategories: 3,
      status: "Now Closed",
      image: "https://www.bookmyhoarding.com/wp-content/uploads/2019/04/compressor-1.jpg",
      profileImage: "https://creativelayers.net/themes/listdo-html/images/resource/user-thumb-2.jpg",
    },
    {
      id: 2,
      featured: true,
      priceRange: "$40 - $60",
      rating: 4,
      reviews: 12,
      name: "Ocean View Resort",
      verified: true,
      description: "Beautiful beachfront billboard with amazing views.",
      location: "Malibu, CA",
      phone: "+61 2 8236 9201",
      category: "Billboard",
      additionalCategories: 2,
      status: "Open Now",
      image: "https://www.bookmyhoarding.com/wp-content/uploads/2019/04/compressor-1.jpg",
      profileImage: "https://creativelayers.net/themes/listdo-html/images/resource/user-thumb-2.jpg",
    },
    {
      id: 3,
      featured: false,
      priceRange: "$30 - $45",
      rating: 4,
      reviews: 9,
      name: "Mountain Retreat",
      verified: false,
      description: "Peaceful billboard in the mountains.",
      location: "Big Bear, CA",
      phone: "+61 2 8236 9202",
      category: "Billboard",
      additionalCategories: 1,
      status: "Open Now",
      image: "https://www.bookmyhoarding.com/wp-content/uploads/2019/04/compressor-1.jpg",
      profileImage: "https://creativelayers.net/themes/listdo-html/images/resource/user-thumb-2.jpg",
    },
    {
      id: 4,
      featured: true,
      priceRange: "$50 - $75",
      rating: 5,
      reviews: 15,
      name: "Downtown Luxury",
      verified: true,
      description: "Modern luxury billboard in the heart of downtown.",
      location: "Los Angeles, CA",
      phone: "+61 2 8236 9203",
      category: "Billboard",
      additionalCategories: 4,
      status: "Open Now",
      image: "https://www.bookmyhoarding.com/wp-content/uploads/2019/04/compressor-1.jpg",
      profileImage: "https://creativelayers.net/themes/listdo-html/images/resource/user-thumb-2.jpg",
    },
    {
      id: 5,
      featured: false,
      priceRange: "$35 - $50",
      rating: 3,
      reviews: 6,
      name: "Sunset Inn",
      verified: false,
      description: "Cozy billboard with beautiful sunset views.",
      location: "Venice Beach, CA",
      phone: "+61 2 8236 9204",
      category: "Billboard",
      additionalCategories: 2,
      status: "Closing Soon",
      image: "https://www.bookmyhoarding.com/wp-content/uploads/2019/04/compressor-1.jpg",
      profileImage: "https://creativelayers.net/themes/listdo-html/images/resource/user-thumb-2.jpg",
    },
    {
      id: 6,
      featured: true,
      priceRange: "$60 - $90",
      rating: 5,
      reviews: 21,
      name: "Grand Plaza Hotel",
      verified: true,
      description: "Elegant billboard with premium amenities.",
      location: "Beverly Hills, CA",
      phone: "+61 2 8236 9205",
      category: "Billboard",
      additionalCategories: 5,
      status: "Open Now",
      image: "https://www.bookmyhoarding.com/wp-content/uploads/2019/04/compressor-1.jpg",
      profileImage: "https://creativelayers.net/themes/listdo-html/images/resource/user-thumb-2.jpg",
    },
    {
      id: 7,
      featured: false,
      priceRange: "$45 - $65",
      rating: 4,
      reviews: 11,
      name: "Harbor View Inn",
      verified: true,
      description: "Scenic views of the harbor and marina billboard.",
      location: "Marina Del Rey, CA",
      phone: "+61 2 8236 9206",
      category: "Billboard",
      additionalCategories: 3,
      status: "Open Now",
      image: "https://www.bookmyhoarding.com/wp-content/uploads/2019/04/compressor-1.jpg",
      profileImage: "https://creativelayers.net/themes/listdo-html/images/resource/user-thumb-2.jpg",
    },
    {
      id: 8,
      featured: true,
      priceRange: "$55 - $80",
      rating: 5,
      reviews: 18,
      name: "Palm Springs Oasis",
      verified: true,
      description: "Desert billboard with spa and pool amenities.",
      location: "Palm Springs, CA",
      phone: "+61 2 8236 9207",
      category: "Billboard",
      additionalCategories: 4,
      status: "Open Now",
      image: "https://www.bookmyhoarding.com/wp-content/uploads/2019/04/compressor-1.jpg",
      profileImage: "https://creativelayers.net/themes/listdo-html/images/resource/user-thumb-2.jpg",
    },
  ]
}
